name 'vagrant-prep-ruby'
maintainer 'pollock'
maintainer_email 'jacksonp2008@gmail.com'
license 'all_rights'
description 'Installs/Configures vagrant-prep-ruby'
long_description 'Installs/Configures vagrant-prep-ruby'
version '0.1.0'

depends 'apt',    '~> 4.0'
depends 'system', '~> 0.11'
depends 'ntp',    '~> 3.2.0'
